theme: dark

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

jwt_secret: "change_this_secret"

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: ["localhost"]
      policy: one_factor

session:
  secret: "change_this_secret"
  expiration: 3600

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notifications.txt
